import "@/styles/globals.css";
import type { AppProps } from "next/app";
import ScrollObserver from "@/utils/scroll-observer";
import SizeObserver from "@/utils/size-observer";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Chain man</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SizeObserver>
        <ScrollObserver>
          <Component {...pageProps} />;
        </ScrollObserver>
      </SizeObserver>
    </>
  );
}
